add x86 support

diff --git a/rootfs/etc/cont-init.d/40-sxfeeder b/rootfs/etc/cont-init.d/40-sxfeeder
--- a/rootfs/etc/cont-init.d/40-sxfeeder
+++ b/rootfs/etc/cont-init.d/40-sxfeeder
@@ -42,6 +42,16 @@ then
     sleep infinity
 fi
 
+# In case sxfeeder cannot be run, let's make sure that qemu exists:
+if ! /usr/bin/sxfeeder --help >/dev/null 2>&1 && ! which qemu-arm-static >/dev/null 2>&1
+then
+    echo ""
+    echo "ERROR: sxfeeder cannot be run natively, and QEMU is not available. You cannot use this container"
+    echo "       on this system / architecture. Feel free to file an issue at https://github.com/sdr-enthusiasts/docker-shipxplorer/issues"
+    echo "Container halted."
+    sleep infinity
+fi
+
 # Create log dirs
 mkdir -p /var/run/sxfeeder
 chmod a+rwx /var/run/sxfeeder
