Update deploy-on-aiscatcher-changes.yml

diff --git a/.github/workflows/deploy-on-aiscatcher-changes.yml b/.github/workflows/deploy-on-aiscatcher-changes.yml
--- a/.github/workflows/deploy-on-aiscatcher-changes.yml
+++ b/.github/workflows/deploy-on-aiscatcher-changes.yml
@@ -2,7 +2,7 @@
 name: Deploy on aiscatcher changes
 on:
   schedule:
-      - cron: "0,15,30,45 * * * *"
+    - cron: "0,15,30,45 * * * *"
   workflow_dispatch:
 
 env:
@@ -22,7 +22,7 @@ jobs:
     steps:
       # Check out our code
       - name: Checkout
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4.1.5
         with:
           fetch-depth: 0
 
@@ -31,43 +31,43 @@ jobs:
           CHECK_CONTAINER: ${{ env.CHECK_CONTAINER }}
           CHECK_TAG: ${{ env.CHECK_TAG }}
         run: |
-            SHA_FILE="aiscatcher.sha"
-            TOKEN="$(curl -sSL "https://ghcr.io/token?scope=repository:$CHECK_CONTAINER:pull" | awk -F'"' '$0=$4')"
-            manifest="$(curl -sSL -H "Accept: application/vnd.oci.image.index.v1+json" -H "Authorization: Bearer ${TOKEN}" "https://ghcr.io/v2/$CHECK_CONTAINER/manifests/$CHECK_TAG")"
-            SHAs_remote="$(echo "$manifest"|jq '.manifests[].digest')"
-            SHAs_remote="${SHAs_remote//$'\n'/}"
+          SHA_FILE="aiscatcher.sha"
+          TOKEN="$(curl -sSL "https://ghcr.io/token?scope=repository:$CHECK_CONTAINER:pull" | awk -F'"' '$0=$4')"
+          manifest="$(curl -sSL -H "Accept: application/vnd.oci.image.index.v1+json" -H "Authorization: Bearer ${TOKEN}" "https://ghcr.io/v2/$CHECK_CONTAINER/manifests/$CHECK_TAG")"
+          SHAs_remote="$(echo "$manifest"|jq '.manifests[].digest')"
+          SHAs_remote="${SHAs_remote//$'\n'/}"
 
-            if grep "error" <<< "$TOKEN $manifest" >/dev/null 2>&1
-            then
-                echo "Error retrieving Token or Manifest."
-                echo "TOKEN=$TOKEN"
-                echo "MANIFEST=$manifest"
-                exit 2
-            fi
-            if [ ! -f "$SHA_FILE" ]; then
-                touch "$SHA_FILE"
-            fi
-            read -r SHAs_local < "$SHA_FILE"
-            # now compare:
-            if [ "$SHAs_local" != "$SHAs_remote" ]; then
-                # we need to rebuild
-                echo "$SHAs_remote" > "$SHA_FILE"
-                git config --local user.name actions-user
-                git config --local user.email "actions@github.com"
-                git add "$SHA_FILE"
-                git commit -am "GH Action SHA updated $(date)"
-                git push -f origin main
-                echo "Success - container needs rebuilding"
-            else
-                echo "Remote container has not changed, no need to run deploy. Exiting."
-                exit 1
-            fi
+          if grep "error" <<< "$TOKEN $manifest" >/dev/null 2>&1
+          then
+              echo "Error retrieving Token or Manifest."
+              echo "TOKEN=$TOKEN"
+              echo "MANIFEST=$manifest"
+              exit 2
+          fi
+          if [ ! -f "$SHA_FILE" ]; then
+              touch "$SHA_FILE"
+          fi
+          read -r SHAs_local < "$SHA_FILE"
+          # now compare:
+          if [ "$SHAs_local" != "$SHAs_remote" ]; then
+              # we need to rebuild
+              echo "$SHAs_remote" > "$SHA_FILE"
+              git config --local user.name actions-user
+              git config --local user.email "actions@github.com"
+              git add "$SHA_FILE"
+              git commit -am "GH Action SHA updated $(date)"
+              git push -f origin main
+              echo "Success - container needs rebuilding"
+          else
+              echo "Remote container has not changed, no need to run deploy. Exiting."
+              exit 1
+          fi
 
   call-workflow-in-local-repo:
-  # Make sure this in the downstream build action:
-  # on:
-  #   workflow_call:
-  #   repository_dispatch:
-  #     types: build_on_aiscatcher_update
+    # Make sure this in the downstream build action:
+    # on:
+    #   workflow_call:
+    #   repository_dispatch:
+    #     types: build_on_aiscatcher_update
     needs: check_upstream_image
     uses: ./.github/workflows/deploy.yml
